name: UAT and Prod deployment

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build_and_deploy_uat:
    runs-on: ubuntu-latest
    environment: uat
    name: Build and Deploy to UAT
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Create .env with Github Secrets
        run: |
          touch .env
          echo VITE_WEATHER_API_URL=${{ secrets.VITE_WEATHER_API_URL }} >> .env
          echo VITE_WEATHER_API_KEY=${{ secrets.VITE_WEATHER_API_KEY }} >> .env
          # npm run script-that-accesses-env-vars
        env:
          VITE_WEATHER_API_URL: ${{ secrets.VITE_WEATHER_API_URL }}
          VITE_WEATHER_API_KEY: ${{ secrets.VITE_WEATHER_API_KEY }}
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_BUSH_07E814710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          # api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
      
      - run: mkdir /tmp/artifacts

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://salmon-bush-07e814710.1.azurestaticapps.net
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true

  deploy_prod:
    runs-on: ubuntu-latest
    name: Deploy to Prod
    environment: prod
    needs: [build_and_deploy_uat]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Create .env with Github Secrets
        run: |
          touch .env
          echo VITE_WEATHER_API_URL=${{ secrets.VITE_WEATHER_API_URL }} >> .env
          echo VITE_WEATHER_API_KEY=${{ secrets.VITE_WEATHER_API_KEY }} >> .env
          # npm run script-that-accesses-env-vars
        env:
          VITE_WEATHER_API_URL: ${{ secrets.VITE_WEATHER_API_URL }}
          VITE_WEATHER_API_KEY: ${{ secrets.VITE_WEATHER_API_KEY }}
      - name: Production deployment
        id: proddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_GROUND_0A897CF10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          # api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
